version: "3.9"

services:
  # ─── Your new Evolution API ───────────────────────────────────────
  evolution-api-new:
    container_name: evo_api_new
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis-new
      - postgres-new
    ports:
      - "8081:8080"               # NEW host port 8081 → container 8080
    env_file:
      - .env                      # or point to a duplicated .env-new if you like
    networks:
      - evo-net-new

  # ─── A brand‑new Redis ───────────────────────────────────────────
  redis-new:
    container_name: evo_redis_new
    image: redis:latest
    restart: always
    command: redis-server --port 6379 --appendonly yes
    ports:
      - "6380:6379"               # NEW host port 6380 → container 6379
    volumes:
      - evo_redis_new:/data
    networks:
      - evo-net-new

  # ─── A brand‑new Postgres ────────────────────────────────────────
  postgres-new:
    container_name: evo_postgres_new
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: evolution
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"              # NEW host port 5433 → container 5432
    volumes:
      - evo_postgres_new:/var/lib/postgresql/data
    networks:
      - evo-net-new

volumes:
  evo_redis_new:
  evo_postgres_new:

networks:
  evo-net-new:
    driver: bridge
